### ISSUE TITLE
are we cleaning up AMIs and snapshots?

### ISSUE THREAD

**Issue by jonasfj** [mozilla-releng/OpenCloudConfig#115]
@grenade, don't we regenerate these AMIs periodically?

Do we delete the old AMIs and snapshots?
 * https://docs.aws.amazon.com/cli/latest/reference/ec2/deregister-image.html
 * https://docs.aws.amazon.com/cli/latest/reference/ec2/delete-snapshot.html

@indygreg found a lot of unused snapshots... taking up a lot of space.

I'm sure we don't cleanup after docker-worker, but we don't rebuild docker-worker very often, and those are all 8GB images too, so I'm less concerned with that... Granted we should obviously clean that up too at some point.

----
Note: Another possibility is that we tag AMIs with an expiration and write a cron job to expired old AMIs and associated snapshots.

Anyways, I'm not sure this is the right place to discuss this... I just suspect that the periodic rebuilding of windows AMIs is the main source of AMIs and snapshots that take up space.

**Comment by indygreg** [comment]
I'm going to extend the housekeeper functionality in taskcluster/ec2-manager to support purging orphaned EBS snapshots belonging to AMIs that no longer exist.

That's the easy problem because we can easily identify when a snapshot is referencing an unknown AMI. Also, AWS doesn't let us delete an AMI snapshot if the AMI is still active. So there's some footgun prevention here.

The harder problem is purging old AMIs (and their associated EBS snapshot). Right now, we seem to accumulate AMIs indefinitely.

I support a process for tagging AMIs with an expiration and periodically deleting old AMIs. We can also have a process that updates the expiration time if an AMI is being used. Old, unused AMIs will eventually be deleted.

**Comment by grenade** [comment]
yes.
https://github.com/mozilla-releng/OpenCloudConfig/search?utf8=%E2%9C%93&q=delete-snapshot+deregister-image&type=

**Comment by grenade** [comment]
occ deletes old amis and snapshots whenever it creates new ones. we keep a small number (2 or 3 per worker type per region) of recent ami/snapshot pairs in order to be able to roll back in the event of a bad deployment.

**Comment by jonasfj** [comment]
hmm, then I'm not sure how we got to have so many unused snapshots... Probably docker-worker :)

I guess garbage collection is a good approach as it ensures we get rid of all the old ones, even when our own processes fails to delete them. I noticed that your scripts where `... || true`, which makes sense.

Unfortunately, EC2 can be slow to realize that the AMI was deregistered, so deleting snapshots could fail, if attempted too quickly after deregistering the AMI (just a theory).

Anyways, GC'ing as gps suggests would fix all of these unfortunate corner cases...

**Comment by indygreg** [comment]
Visually scanning through the AMIs, nearly all of them have `docker-worker` in their name.

Some of the deleted EBS snapshots were quite large - 120 GB. I don't think anything in docker-worker land creates AMIs that large. Maybe they did once upon a time. I wouldn't count out the theory that snapshot deletion is fully working and we're orphaning snapshots we deregistering AMIs. I still think purging orphaned snapshots in ec2-manager is a good idea.
